spring:
  application:
    name: InteractiveSpeciesAtlas_v3
  datasource:
    url: jdbc:postgresql://localhost:5432/interactive_atlas_species_api_db # ${SPRING_DATASOURCE_URL}
    username: postgres # ${SPRING_DATASOURCE_USERNAME}
    password: Test1234= # ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    cache-names:
      - vernacularName
      - species
      - description
    caffeine:
      spec: maximumSize=500,expireAfterWrite=6h

server:
  port: 8080

openai:
  api:
    key: "your key"

